project:
  type: website
  output-dir: _site
  execute-dir: project
  render:
    - index.qmd
    - "!week*.qmd"

website:
  title: "Ph.D. Applied Microeconometrics"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: assignments
        text: Assignments

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 2
